### Bestillinger ###

POST http://localhost:8080/bestillinger
Content-Type: application/json

{
  "orderId": 0,
  "customerName": "",
  "movieTitle": ""
}

<> 2024-03-16T120628.404.json
<> 2024-03-16T114907.404.json
###
GET http://localhost:8080/bestillinger

### Kjøp Billett ###

POST http://localhost:8080/kjopbillett
Content-Type: application/x-www-form-urlencoded

<> 2024-03-16T120729.400.json
###
GET http://localhost:8080/kjopBilletter

### Slett Alle Billetter ###

GET http://localhost:8080/slettAlleBilletter

POST http://localhost:8080/slettAlleBilletter
Content-Type: application/x-www-form-urlencoded



